### ISSUE TITLE
Icons for Categories

### ISSUE THREAD

**Issue by jlzych** [privacypatterns/privacypatterns#37]
And for patterns that are targeted to front-end devs, or back-end devs, or lawyers, or managers, etc.

**Comment by p4pnl** [comment]
Here's my suggestions for the strategy categories. Each image is based on a Creative Commons item in [thenounproject.com](https://thenounproject.com) as recommended above. They are all modified, though 'inform' is just rotated and resized. Attribution links included in text.

[INFORM](https://thenounproject.com/jamison)|[NOTIFY](https://thenounproject.com/nazl%C4%B1)|[DEMONSTRATE](https://thenounproject.com/windy.windysky)|[ENFORCE](https://thenounproject.com/marekpolakovic)
-----|-----|-----|-----
![inform](https://cloud.githubusercontent.com/assets/22982361/23220194/73889002-f921-11e6-9e14-4434382b93a0.png)|![notify](https://cloud.githubusercontent.com/assets/22982361/23220195/73967172-f921-11e6-992f-42ca757aa68c.png)|![demonstrate](https://cloud.githubusercontent.com/assets/22982361/23220192/73860df0-f921-11e6-92f6-a13217b69cab.png)|![enforce](https://cloud.githubusercontent.com/assets/22982361/23220191/73851350-f921-11e6-9e67-a3e6dffacb39.png)
[ABSTRACT](https://thenounproject.com/AlfredoCreates)|[MINIMIZE](https://thenounproject.com/Templarian)|[SEPARATE](https://thenounproject.com/icon54app)|[HIDE](https://thenounproject.com/kozinn)
![abstract](https://cloud.githubusercontent.com/assets/22982361/23220190/7384f9a6-f921-11e6-911c-6138506350de.png)|![minimize](https://cloud.githubusercontent.com/assets/22982361/23220193/7387c032-f921-11e6-8f89-2341d62fd029.png)|![separate](https://cloud.githubusercontent.com/assets/22982361/23220196/739792dc-f921-11e6-84fe-90610e40bb3a.png)|![hide](https://cloud.githubusercontent.com/assets/22982361/23220189/7384ebfa-f921-11e6-9e16-0f07254c7c84.png)

**Comment by p4pnl** [comment]
Here's a hypothetical example screen cap (with more applicable categories than we'd like)
![capture](https://cloud.githubusercontent.com/assets/22982361/23221774/3d718c30-f926-11e6-90e1-b20ee5334195.JPG)

**Comment by xot** [comment]
Michael showed me these yesterday. Funnily enough I'd been thinking of an iconset independently of him a month ago or so. Here they are:
![icons](https://cloud.githubusercontent.com/assets/5526427/24167174/10984356-0e76-11e7-9f32-9026f41112fa.gif)

**Comment by p4pnl** [comment]
I added some new variations after feedback from various sources.

[ ](allow-my-table-to-use-div,-please)<div title="Derivative, checkbox">[DEMONSTRATE](https://thenounproject.com/andimukticahyono123/)</div>|<div title="Derivative, shield">[ENFORCE](https://thenounproject.com/marekpolakovic)</div>|<div title="Original Work">MINIMIZE</div>|<div title="Derivative, webcam">[HIDE](https://thenounproject.com/nonoesp/)</div>
-----|-----|-----|-----
![demonstrate](https://user-images.githubusercontent.com/22982361/28215180-5b0a9826-68ad-11e7-941c-732b90e4cf4b.png)|![enforce](https://user-images.githubusercontent.com/22982361/28215208-795bd34e-68ad-11e7-9dc8-8758703a6533.png)|![minimize](https://user-images.githubusercontent.com/22982361/28215269-a7357446-68ad-11e7-9ca3-9dac4731bf88.png)|![hide](https://user-images.githubusercontent.com/22982361/28215369-132b43ec-68ae-11e7-89fb-27ef65c66a8a.png)

**Comment by npdoty** [comment]
I like these a lot! I don't know if this should be finished; I feel like a graphic designer might suggest more consistency in design or we might learn which ones are effective and which ones are confusing. But in any case this is a great step. (I'm reviewing the PR now.)

**Comment by xot** [comment]
Dear all,

I think some are a bit complex and therefore confusing. I've been using
the ones in the figure attached for some time in my presentations, and
they seem to resonate well...

On 18/07/2017, 00:22, Nick Doty wrote:
> I like these a lot! I don't know if this should be finished; I feel like a graphic designer might suggest more consistency in design or we might learn which ones are effective and which ones are confusing. But in any case this is a great step. (I'm reviewing the PR now.)
> 

-- 
Jaap-Henk Hoepman            |  Sure! We've eaten off the silver
Scientific Director          |  (when even food was against us)
Privacy & Identity Lab       |    - The Birthday Party "Just You and Me"
Radboud University Nijmegen  |
                             |
(w) www.cs.ru.nl/~jhh        | (w) www.pilab.nl
(e) jhh@cs.ru.nl             | (m) +31 6 20619554
    PGP id: 895311AD         | (t) @xotoxot
    PGP fingerprint : BAB7 1CBA 261F A867 DF38 1F21 1863 2788 8953 11AD

**Comment by npdoty** [comment]
We merged initial icons for strategies back in July, so closing this. 

@xot if you have improved icons, feel free to send to the mailing list or open a PR with improved iconography. (In your previous message, the attachment got stripped by Github.)
