### ISSUE TITLE
docker/next doesn't support multiviews/extensionless access

### ISSUE THREAD

**Issue by npdoty** [privacypatterns/privacypatterns#60]
This loads: https://next.privacypatterns.org/patterns/Ambient-notice.html
But this returns 404: https://next.privacypatterns.org/patterns/Ambient-notice

**Comment by npdoty** [comment]
I believe this will be fixed by 27da42e8011af729beb16e6a0cd1e92b0b559aa3, #62.

**Comment by mohit** [comment]
fixed by #62
