### ISSUE TITLE
Update about page / bio information

### ISSUE THREAD

**Issue by npdoty** [privacypatterns/privacypatterns#63]
1. Updated affiliation/link information for Berkeley/privacypatterns.org folks
2. Start adding links/logos for EU collaborators

**Comment by p4pnl** [comment]
See [this HTML snippet](https://github.com/privacypatterns/privacypatterns/files/793562/part.txt) for an update on the privacypatterns.eu affiliations HTML and CSS (for moving to main.css). Image paths can be swapped with local variants and updated for anyone who has changed affiliation (@mohit ?).

**Comment by mohit** [comment]
@p4pnl thanks for the note. Here is the update to the HTML snippet: https://gist.github.com/mohit/5d455b9bd9d5c5079c693a32bc5bb4a7

**Comment by mohit** [comment]
I've also made a merge request on the paper here https://gitlab-vs.informatik.uni-ulm.de/papers/collab-privacy-pattern/merge_requests/1

**Comment by mohit** [comment]
@npdoty deployed you can see changes here: https://privacypatterns.org/about/

or https://privacypatterns.org/changes
