### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by npdoty** [privacypatterns/privacypatterns#78]
While categories/browsing is a higher priority, can we also add search functionality to a static site?

Potentially useful URL: http://stackoverflow.com/a/28611848/108575

**Comment by olhadrozd** [comment]
Hi Nick,

I've implemented a search functionality, but I cannot push (create branch and PR) it to the repo. It seems I don't have permissions for that. Could you please have a look at this issue?

Thanks
Olha

**Comment by npdoty** [comment]
pull request #80 from Olha will address this issue
